#!/bin/sh
set -e

VER="0.1.7a"

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/bin/samtools-hybrid ]; then
    for filename in samtools-hybrid razip blast2sam.pl bowtie2sam.pl export2sam.pl interpolate_sam.pl novo2sam.pl psl2sam.pl sam2vcf.pl samtools.pl soap2sam.pl wgsim_eval.pl zoom2sam.pl md5sum-lite md5fa maq2sam-short maq2sam-long wgsim; do
        update-alternatives --remove ${filename} /usr/bin/${filename}${VER}
    done
fi
